### PR TITLE
feat: Add default platform for alpine linux

### LINKED ISSUE #28: Crash while auto-detecting platform name on Alpine Linux
When `pip-custom-platform` is used without an explicit `--platform` parameter (i.e. platform auto-detection is used) on Docker image of Python on Alpine Linux, it crashes with the following exception:

```shell
# pip-custom-platform show-platform-name
Traceback (most recent call last):
  File "/usr/local/bin/pip-custom-platform", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 261, in entry
    tuple(patches) + ('--', original_entry_point) + tuple(argv)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 249, in main
    return entry.load()()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 25, in <module>
    from pip._internal.index import PackageFinder
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 164, in load_module
    module = importmod(fullname)
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 94, in importmod
    return __import__(mod, fromlist=[str('__name__')], level=0)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/index.py", line 32, in <module>
    from pip._internal.pep425tags import get_supported
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pymonkey.py", line 166, in load_module
    hook_fn(module, self._entry_data[entry])
  File "/usr/local/lib/python3.6/site-packages/pip_custom_platform/pymonkey.py", line 17, in pymonkey_patch
    mod.supported_tags = mod.get_supported()
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/pep425tags.py", line 340, in get_supported
    if is_manylinux2010_compatible():
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/pep425tags.py", line 196, in is_manylinux2010_compatible
    return pip._internal.utils.glibc.have_compatible_glibc(2, 12)
AttributeError: module 'pip' has no attribute '_internal'
```

A similar exception is raised on Python 2.7, 3.6 and 3.7 Docker images on Alpine Linux. It can be reproduced e.g. by running `docker build .` with the following `Dockerfile`:

```Dockerfile
FROM python:3.6-alpine3.9
  
RUN pip install pip-custom-platform && \
    pip-custom-platform install --platform=linux_alpine3_9_x86_64 pip && \
    pip-custom-platform show-platform-name
```

The first `pip-custom-platform` command, where an explicit platform is provided, works fine. The second one, where auto-detection is supposed to be used, crashes with the above-mentioned exception.

Platform auto-detection seems to work fine e.g. on Debian.

### PR DESCRIPTION
**Pull request by aexvir**
This should close #28

### CODE REVIEW

**Comment by aexvir** [comment]
The failing tests don't seem related to my changes... or at least not at a first glance 🤔

**Comment by asottile** [comment]
one question about alpine but otherwise seems fine -- does alpine guarantee a strata of packages for a minor version or is it more of a rolling release?  if it's the latter, providing a platform name isn't really appropriate (since it's a moving target and dynamic linking will fail at a later date as the moving target... well... moves)

**Comment by aexvir** [comment]
> one question about alpine but otherwise seems fine -- does alpine guarantee a strata of packages for a minor version or is it more of a rolling release? if it's the latter, providing a platform name isn't really appropriate (since it's a moving target and dynamic linking will fail at a later date as the moving target... well... moves)

Hmm... not sure if I'm understanding your question. As far as I know, alpine edge could be considered somewhat a rolling release, but the fixed versions aren't. Each version has its own set of packages like [here](https://pkgs.alpinelinux.org/packages?name=&branch=v3.11)

**Comment by aexvir** [comment]
But I'd say that most of the cases where alpine is used is for Docker images used in deployments, where the whole environment is isolated and re-built every time a new release is launched, and not really on end user machines.

**Comment by asottile** [comment]
sounds like the answer is "yes" -- basically if I were to build an image against 3.11 in a few years it would still use the same set of packages / C-apis 👍

**Comment by aexvir** [comment]
Yep, right now if you install `python3` on `alpine:3.3` you'll get `3.5.1`, for example 🙂 
https://pkgs.alpinelinux.org/packages?name=python3&branch=v3.3

**Pull request merged**
