### PR TITLE
Replace deprecated platform.linux_distribution with distro

### LINKED ISSUE #14: Switch from `platform.linux_distribution` to `distro`
This will be removed in [python 3.7](https://docs.python.org/3.5/library/platform.html#platform.linux_distribution)

I've used `distro` successfully [here](https://github.com/asottile/rubyvenv/blob/621d924a1cd55b371d5f7208a3f151b496a98bf6/rubyvenv.py#L64-L65)

### PR DESCRIPTION
**Pull request by asottile**
Resolves #14

### CODE REVIEW

**Comment by asottile** [comment]
CC @chriskuehl

**Comment by chriskuehl** [comment]
heh, did you actually test the docker tests? i'd be amazed if they're not completely bitrotted

**Comment by asottile** [comment]
> heh, did you actually test the docker tests? i'd be amazed if they're not completely bitrotted

I did! they're about 10 minute round-trip to debug but they all pass again

**Pull request merged**
