### PR TITLE
Add support for amazon linux

### PR DESCRIPTION
**Pull request by bakkerthehacker**

### CODE REVIEW

**Comment by asottile** [comment]
Can you show me the output of the docker test (since it doesn't run in ci)

**Comment by bakkerthehacker** [comment]
@asottile master has some unrelated rhel failures on make docker-tests

https://gist.github.com/bakkerthehacker/183fe5d3ebd6c3490cdd13cb90c77c2c

**Comment by asottile** [comment]
Yeah, safe to ignore the rhel stuff.  They don't exactly provide a docker image or interpreter being nonfree and all.  I might consider dropping that test since it provides dubious-at-best value.

**Comment by asottile** [comment]
Thanks!

**Comment by asottile** [comment]
This has been released as v0.4.1 -- thanks again!

**Comment by bakkerthehacker** [comment]
Thanks for the quick merge and release :3

**Pull request merged**
